spring.config.import=optional:file:.env[.properties]

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA:public},public
spring.datasource.driver-class-name=org.postgresql.Driver


spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 3. Docker Compose Settings
spring.docker.compose.file=compose.yaml
spring.docker.compose.enabled=true
# Use 'active' to ensure Spring stays connected to the container it started
spring.docker.compose.lifecycle-management=start_only

app.cors.allowed-origins=${FRONTEND_URL}

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.datasource.hikari.schema=${DB_SCHEMA:public}

spring.liquibase.default-schema=${DB_SCHEMA:public}
spring.liquibase.liquibase-schema=${DB_SCHEMA:public}
spring.liquibase.rollback-on-error=true
logging.level.liquibase=debug

server.port=${PORT:8080}
app.security.password.min-length=12
app.security.password.require-special-chars=true

management.endpoints.web.exposure.include=refresh

spring.cloud.bootstrap.enabled=true

# Tell Spring to pass the env file to the docker command it runs
spring.docker.compose.skip.in-tests=false

logging.level.org.springframework.jdbc.core.simple.JdbcClient=DEBUG
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=TRACE

# Shows Spring Security filter chain decisions
logging.level.org.springframework.security=DEBUG


spring.sql.init.mode=never


app.defaults.nested-group-id=123e4567-e89b-12d3-a456-426614174000
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000



